### ISSUE TITLE
Use of undefined constant DEVELOPER_NAME

### ISSUE THREAD

**Issue by viktorix** [azurecurve/azrcrv-smtp#11]
Noticed this in the logs on a site that's using SMTP plugin.
`Use of undefined constant DEVELOPER_NAME - assumed 'DEVELOPER_NAME' (this will throw an Error in a future version of PHP)`

File: `/wp-content/plugins/azrcrv-smtp/includes/azurecurve-menu-tabs-output.php`
Line: 50

This is ClassicPress v2.0 nightly on PHP 7.4.33.

**Comment by azurecurve** [comment]
2.1.4 has been released to fix this issue.
