### ISSUE TITLE
Feature request: import settings from Easy WP SMTP

### ISSUE THREAD

**Issue by xxsimoxx** [azurecurve/azrcrv-smtp#2]
Since I had to convert some sites to your plugin and forgot 50% of SMTP passwords I've implemented the code to do this and so **if you like this feature it is nearly ready for a PR**. Just a bit of testing...

I've done it in a very discrete way:
- When you activate the plugin, if there are already settings for Easy WP SMTP, they are automatically used as defaults
- If somethings goes wrong no message will appear, just empty settings as usual
- If everything is fine, you'll get a one-time message in your settings page

**Comment by azurecurve** [comment]
How about presenting an option on the settings page, when their are no settings in the database, allowing import, rather than simply importing without asking?
