### ISSUE TITLE
Warning on `admin_init`

### ISSUE THREAD

**Issue by xxsimoxx** [azurecurve/azrcrv-smtp#4]
The function hooked [here](https://github.com/azurecurve/azrcrv-smtp/blob/8e76047fb86c7db57fd21c4711e8c21515ff05cb/azrcrv-smtp.php#L27) does not exists.
So this warning is generated:
`PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'azrcrv_create_plugin_menu_smtp' not found or invalid function name in /var/w....ocs/wp-includes/class-wp-hook.php on line 286`

Seems that in `pluginmenu/menu.php` the function has been renamed to `azrcrv_populate_plugin_menu_r`.

**Comment by azurecurve** [comment]
I've released 1.4.1 which fixes this issue.

My fault for missing it; I created a new test site and forget to enable debug.

Thanks for the report.

**Comment by xxsimoxx** [comment]
Thank you. Fixed!
