### ISSUE TITLE
PHP notice when sending test email

### ISSUE THREAD

**Issue by xxsimoxx** [azurecurve/azrcrv-smtp#5]
`PHP Notice: Undefined variable: error in /var/www/vhosts/educatorecinofilo.dog/httpdocs/wp-content/plugins/azrcrv-smtp/azrcrv-smtp.php on line 798`

**Comment by azurecurve** [comment]
I've released 1.4.2 which should resolve this error.

**Comment by xxsimoxx** [comment]
Thanks!
