### ISSUE TITLE
Missing PHPMailer exceptions

### ISSUE THREAD

**Issue by xxsimoxx** [azurecurve/azrcrv-smtp#8]
# Steps to reproduce

- in the setting change the username to a wrong one
- sent test e-mail

# Possible fix 
Seems that after [this line](https://github.com/azurecurve/azrcrv-smtp/blob/d25768869500b73ab06e3c226d92d7da7123cfe2/includes/plugin-functionality.php#L174) you should add
`require_once ABSPATH . WPINC . '/PHPMailer/Exception.php';`

**Comment by azurecurve** [comment]
Can reproduce error and tested proposed fix. A new version will be released later today after some further testing.
